In [2]:
import numpy as np

# Write a function that takes as input a list of numbers, and returns
# the list of values given by the softmax function.
def softmax(L):
    expL = np.exp(L)
    sumExpL = sum(expL)
    return expL / sumExpL

softmax([5, 6, 7])

[5, 6, 7]
[ 148.4131591   403.42879349 1096.63315843]


[0.09003057317038046, 0.24472847105479764, 0.6652409557748219]

In [4]:
L = np.exp([5, 6, 7])
L

array([ 148.4131591 ,  403.42879349, 1096.63315843])

In [5]:
sum(L)

1648.4751110237703

In [8]:
L/sum(L)

array([0.09003057, 0.24472847, 0.66524096])